# Generated by Django 3.1.6 on 2021-03-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210327_1943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
